spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 기존 유저테이블이 있어도 프로젝트를 실행할때마다 실행함
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false # 기본 넘버링을 따라가지 않음
    show-sql: true
    properties:
      hibernate.format_sql: true #sql을 정렬해서 띄워줌

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8001
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true


